---
- name: Delete localtime file
  become: yes
  file:
    path: /etc/localtime
    state: absent

- name: Change timezone to ET
  become: yes
  file:
    src:  /usr/share/zoneinfo/America/New_York
    dest: /etc/localtime
    state: link

- name: Clone the repo
  git:
    repo: "https://{{GH_USER}}:{{GH_PASS}}@github.ncsu.edu/engr-csc326-staff/iTrust2-v6.git"
    dest: '{{ansible_env.HOME}}/iTrust2-v6'

- name: Copy Fuzzer logic (main.js)
  become: yes
  template:
    src: main.js.j2
    dest: '{{ansible_env.HOME}}/main.js'

- name: Copy package.json
  become: yes
  template:
    src: package.json
    dest: '{{ansible_env.HOME}}/package.json'

- name: Install node modules based on package.json
  become: yes
  npm:
    path: '{{ansible_env.HOME}}'

- name: copy db.properties
  become: yes
  template:
    src: db.properties.j2
    dest: '{{ansible_env.HOME}}/iTrust2-v6/iTrust2/src/main/java/db.properties'

- name: copy email.properties
  become: yes
  template:
    src: email.properties.j2
    dest: '{{ansible_env.HOME}}/iTrust2-v6/iTrust2/src/main/java/email.properties'