---
- name: Installing pip
  become: yes
  apt:
    name: python3-pip
    state: present

- name: Installing jenkins job builder
  become: yes
  apt:
    name: python3-jenkins-job-builder
    state: present

- name: Get crumb
  uri:
    url: http://127.0.0.1:9000/crumbIssuer/api/json
    user: "{{JK_USR}}"
    password: "{{JK_PASSWD}}"
    force_basic_auth: yes
  register: result

- name: Generate Access token
  uri:
    url: http://127.0.0.1:9000/me/descriptorByName/jenkins.security.ApiTokenProperty/generateNewToken
    method: POST
    user: "{{JK_USR}}"
    password: "{{JK_PASSWD}}"
    body_format: form-urlencoded
    body:
      newTokenName: job
      Jenkins-Crumb: "{{result.json.crumb}}"
    force_basic_auth: yes
  register: token

- name: print data
  debug:
    msg: "{{token.json.data.tokenValue}}"

  
- name: create a jenkins_jobs directory
  become: yes
  file:
    path: /etc/jenkins_jobs
    state: directory
    mode: '0755'
  
- name: push the jenkins_jobs.ini into the folder
  become: yes
  template:
    src: jenkins_jobs.ini.j2
    dest: /etc/jenkins_jobs/jenkins_jobs.ini
    mode: 0755
    owner: jenkins

- name: push the yml file
  become: yes
  template:
    src: checkbox.yml.j2
    dest: /var/lib/jenkins/jobs/hello.yml
    mode: 0755
    owner: jenkins

- name: create job
  become: yes
  shell: 
    cmd: jenkins-jobs update jobs
  args:
    chdir: /var/lib/jenkins
    
- name: Trigger the build job
  uri: 
    url: http://127.0.0.1:9000/job/checkbox/build
    method: POST
    user: "{{JK_USR}}"
    password: "{{JK_PASSWD}}"
    body_format: form-urlencoded
    body:
      newTokenName: job
      Jenkins-Crumb: "{{result.json.crumb}}"
    force_basic_auth: yes
    status_code: 201
  register: token
