
- hosts: monitor
  roles:
   - ping
  #  - update
  #  - monitor

- hosts: checkbox.io
  roles:
    - ping
    # - update
    # - server

- hosts: iTrust
  roles:
    - ping
    # - update
    # - server