---
- name: Generate token for Jenkins build
  include_tasks: token.yml

- name: Installing jenkins job builder
  become: yes
  apt:
    name: python3-jenkins-job-builder
    state: present

- name: Install pm2
  become: yes
  npm:
    name: pm2
    global: yes
    state: latest

- name: create a jenkins_jobs directory
  become: yes
  file:
    path: /etc/jenkins_jobs
    state: directory
    mode: '0755'

- name: push the jenkins_jobs.ini into the folder
  become: yes
  template:
    src: jenkins_jobs.ini.j2
    dest: /etc/jenkins_jobs/jenkins_jobs.ini
    mode: 0755
    owner: jenkins

- name: push the checkbox yml file
  become: yes
  template:
    src: checkbox.yml.j2
    dest: /var/lib/jenkins/jobs/checkbox.yml
    mode: 0755
    owner: jenkins

- name: push the iTrust yml file
  become: yes
  template:
    src: itrust.yml.j2
    dest: /var/lib/jenkins/jobs/itrust.yml
    mode: 0755
    owner: jenkins

- name: create jobs
  become: yes
  shell: 
    cmd: jenkins-jobs update jobs
  args:
    chdir: /var/lib/jenkins
