---
- name: Installing pip
  become: yes
  apt:
    name: python3-pip
    state: present

- name: Installing jenkins job builder
  become: yes
  apt:
    name: python3-jenkins-job-builder
    state: present

- name: Install pm2
  become: yes
  npm:
    name: pm2
    global: yes
    state: latest
  