---
- name: Install nodejs
  include: node.yml

- name: Install forever - global
  become: yes
  npm:
    name: forever
    global: yes

- name: Install node-modules
  become: yes
  npm:
    path: /home/vagrant/checkbox.io-micro-preview/
  
