---
- name: Adding environmental variables in/etc/bash.bashrc (System-wide)
  become: yes
  lineinfile:
    path: "/etc/bash.bashrc"
    insertbefore: 'BOF'
    line: export "{{item}}"
    state: present
  with_items:
    - APP_PORT=3002
    - MONGO_PORT=27012
    - MONGO_USER="{{MO_USR}}"
    - MONGO_PASSWORD="{{MO_PASSWD}}"
    - MONGO_IP=localhost


- name: Adding environmental variables in /etc/environment
  become: yes
  lineinfile:
    path: "/etc/environment"
    insertbefore: 'BOF'
    line: export "{{item}}"
    state: present
  with_items:
    - APP_PORT=3002
    - MONGO_PORT=27012
    - MONGO_USER="{{MO_USR}}"
    - MONGO_PASSWORD="{{MO_PASSWD}}"
    - MONGO_IP=localhost
