---
    - name: Install openjdk-8-jdk
      apt: 
        name: openjdk-8-jdk
        state: present
      become: true

    - name: Add an Apt signing key, uses whichever key is at the URL
      apt_key:
        url: https://pkg.jenkins.io/debian/jenkins.io.key
        state: present
      become: true

    - name: Add jenkins repository to the resource list
      lineinfile:
        path: /etc/apt/sources.list.d/jenkins.list
        line: deb http://pkg.jenkins.io/debian-stable binary/
        create: yes
      become: true

    - name: Update cache
      apt:
        update_cache: yes
      become: true

    - name: Install jenkins
      apt:
        name: jenkins
        state: latest
      become: true

    - name: Allow all access to port 8080
      ufw:
        rule: allow
        port: '8080'
      become: true

    - name: Modify port to 9000
      lineinfile:
        dest
      

    

      

    