# - name: push redis script
#   become: yes
#   template:
#     src: met.js.j2
#     dest: /home/vagrant/met.js
#     mode: 0664
#     owner: vagrant

# - name: push redis package.json
#   bacome: yes
#   template:
#     src: package.json
#     dest: /home/vagrant/package.json
#     mode: 0664
#     owner: vagrant

# - name: do i have to start redis?

- name: Recursively remove directory
  file:
    path: /home/vagrant/checkbox.io-micro-preview/
    state: absent

- git:
    repo: 'https://github.com/chrisparnin/checkbox.io-micro-preview.git'
    dest: /home/vagrant/checkbox.io-micro-preview
    version: "{{BLUE_BRANCH}}"

- name: Stop all services
  command: forever stopall

- name: Install node-modules
  become: yes
  npm:
    path: /home/vagrant/checkbox.io-micro-preview/

- name: Start the server
  shell:
    cmd: forever start index.js
  args: 
    chdir: /home/vagrant/checkbox.io-micro-preview