---
- name: Get crumb
  uri:
    url: http://192.168.33.20:9000/crumbIssuer/api/json
    user: "{{JK_USR}}"
    password: "{{JK_PASSWD}}"
    force_basic_auth: yes
  register: result

- name: Create Credentials
  uri:
    url: http://192.168.33.20:9000/credentials/store/system/domain/_/createCredentials
    method: POST
    user: "{{JK_USR}}"
    password: "{{JK_PASSWD}}"
    body_format: form-urlencoded
    headers:
        Jenkins-Crumb: "{{result.json.crumb}}"
    body: |
        json={
            "": "0",
            "credentials": {
                "scope": "GLOBAL",
                "id": "{{credentials_id}}",
                "username": "{{email_username}}",
                "password": "{{email_password}}",
                "description": "iTrust",
                "$class": "com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl"
            }
        } 
    force_basic_auth: yes
    status_code: 302
