---
- name: Get crumb
  uri:
    url: http://192.168.33.20:9000/crumbIssuer/api/json
    user: "{{JK_USR}}"
    password: "{{JK_PASSWD}}"
    force_basic_auth: yes
  register: result

- name: Get Latest Job URL - before trigger
  become: yes
  uri:
    url: "http://192.168.33.20:9000/job/checkbox.io/api/json?pretty=true?"
    method: POST
    user: "{{JK_USR}}"
    password: "{{JK_PASSWD}}"
    body_format: form-urlencoded
    body:
      Jenkins-Crumb: "{{result.json.crumb}}"
    force_basic_auth: yes
  register: latest_job_before
  
# - debug: 
#     msg: "{{latest_job_before}}"
    
- name: Trigger the build Job
  become: yes
  uri: 
    url: "http://192.168.33.20:9000/job/checkbox.io/build"
    method: POST
    user: "{{JK_USR}}"
    password: "{{JK_PASSWD}}"
    body_format: form-urlencoded
    body:
      Jenkins-Crumb: "{{result.json.crumb}}"
    force_basic_auth: yes
    status_code: 201
  register: build_reply

# - debug: 
#     msg: "{{build_reply}}"

# - pause:
#     seconds: 45

- name: Get Latest Job - non null
  become: yes
  uri:
    url: "http://192.168.33.20:9000/job/checkbox.io/api/json?pretty=true?"
    method: POST
    user: "{{JK_USR}}"
    password: "{{JK_PASSWD}}"
    body_format: form-urlencoded
    body:
      Jenkins-Crumb: "{{result.json.crumb}}"
    force_basic_auth: yes
  register: latest_job_non_null
  until: latest_job_non_null.json.lastCompletedBuild > 0
  retries: 50
  delay: 10
  

# - debug: 
#     msg: "{{latest_job_non_null}}"

- name: Get Latest Job URL - after trigger
  become: yes
  uri:
    url: "http://192.168.33.20:9000/job/checkbox.io/api/json?pretty=true?"
    method: POST
    user: "{{JK_USR}}"
    password: "{{JK_PASSWD}}"
    body_format: form-urlencoded
    body:
      Jenkins-Crumb: "{{result.json.crumb}}"
    force_basic_auth: yes
  register: latest_job_after_trigger
  until: latest_job_after_trigger.json.lastCompletedBuild.number==latest_job_before.json.nextBuildNumber
  retries: 50
  delay: 10

# - debug: 
#     msg: "{{latest_job}}"

- debug: 
    msg: "{{latest_job_after_trigger.json.lastCompletedBuild.url}}"

# - name: API call to get the console output
#   become: yes
#   shell: curl {{latest_job_after_trigger.json.lastCompletedBuild.url}}consoleText --user {{JK_USR}}:{{JK_PASSWD}}
#   register: curl_op

# - debug: 
#     msg: "{{curl_op.stdout_lines}}"
